blogger_blog_list:
    pattern: /
    defaults: { _controller: BlogBundle:Blog:list }

blogger_comment_create:
    pattern:  /comment
    defaults: { _controller: BlogBundle:Comment:create }
    requirements:
        _method: GET
