admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

forum:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /forum/