<?php

namespace UserBundle\Entity;

/**
 * Belong1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Belong1Repository extends \Doctrine\ORM\EntityRepository
{
	public function getBelong1Relations($limit = null)
	{
		$qp = $this->createQueryBuilder('b')->select('b');

		if (false === is_null($limit))
			$qp->setMaxResults($limit);

		return $qp->getQuery()->getResult();
	}
}