<?php

namespace UserBundle\Entity;

/**
 * CompeteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompeteRepository extends \Doctrine\ORM\EntityRepository
{
	public function getCompeteRelations($limit = null)
	{
		$qp = $this->createQueryBuilder('c')->select('c');

		if (false === is_null($limit))
			$qp->setMaxResults($limit);

		return $qp->getQuery()->getResult();
	}
}