<?php

namespace UserBundle\Entity;

/**
 * ElevenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElevenRepository extends \Doctrine\ORM\EntityRepository
{
	public function getEleven($limit = null)
	{
		$qp = $this->createQueryBuilder('e')->select('e');

		if (false === is_null($limit))
			$qp->setMaxResults($limit);

		return $qp->getQuery()->getResult();
	}
}