<?php

namespace UserBundle\Entity;

/**
 * LeagueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeagueRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLeagues($limit = null)
	{
		$qp = $this->createQueryBuilder('l')->select('l');

		if (false === is_null($limit))
			$qp->setMaxResults($limit);

		return $qp->getQuery()->getResult();
	}
}