<?php

namespace UserBundle\Entity;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPlayers($limit = null)
	{
		$qp = $this->createQueryBuilder('p')->select('p')->addOrderBy('p.name', 'DESC');

		if (false === is_null($limit))
			$qp->setMaxResults($limit);

		return $qp->getQuery()->getResult();
	}
}