user_index:
    pattern: /
    defaults: { _controller: UserBundle:User:index }

user_login:
    pattern: /login
    defaults: { _controller: UserBundle:User:login }
    requirements:
        _method: GET

user_loginAttempt:
    pattern: /login
    defaults: { _controller: UserBundle:User:loginAttempt }
    requirements:
        _method: POST

user_signup:
    pattern: /signup
    defaults: { _controller: UserBundle:User:signup }
    requirements:
        _method: GET

user_signupAttempt:
    pattern: /signup
    defaults: { _controller: UserBundle:User:signupAttempt }
    requirements:
        _method: POST

user_exit:
    pattern: /exit
    defaults: { _controller: UserBundle:User:exit }

user_listTeams:
    pattern: /teams
    defaults: { _controller: UserBundle:Team:listTeams }

user_leaguePassword:
    pattern: /teams/league/{league_id}
    defaults: { _controller: UserBundle:League:leaguePassword }
    requirements:
        league_id:  \d+
        _method: GET

user_checkLeaguePassword:
    pattern: /teams/league/{league_id}
    defaults: { _controller: UserBundle:League:leaguePassword }
    requirements:
        league_id:  \d+
        _method: POST

user_newTeam:
    pattern: /teams/new/{league_id}
    defaults: { _controller: UserBundle:Team:newTeam }
    requirements:
        _method: GET
        league_id:  \d+

user_createTeam:
    pattern: /teams/create/{league_id}
    defaults: { _controller: UserBundle:Team:createTeam }
    requirements:
        _method: POST
        league_id:  \d+

user_showRanking:
    pattern: /teams/ranking
    defaults: {_controller: UserBundle:Team:showRanking }

user_updateEleven:
    pattern: /teams/eleven/update
    defaults: { _controller: UserBundle:Team:updateEleven }

user_showTeam:
    pattern: /teams/{edit}
    defaults: { _controller: UserBundle:Team:showTeam }
    requirements:
        league_id:  \d+

user_saveTeam:
    pattern: /teams/{league_id}/{team_id}
    defaults: { _controller: UserBundle:Team:saveTeam }
    requirements:
        league_id:  \d+
        team_id:  \d+

user_editEleven:
    pattern: /teams/edit
    defaults: { _controller: UserBundle:Team:editEleven }

user_listLeagues:
    pattern: /leagues/join
    defaults: { _controller: UserBundle:League:listLeagues }

user_newLeague:
    pattern: /leagues/new
    defaults: { _controller: UserBundle:League:newLeague }

user_createLeague:
    pattern: /leagues/create
    defaults: { _controller: UserBundle:League:createLeague }

user_showPlayer:
    pattern: /viewplayer/{player_id}
    defaults: {_controller: UserBundle:Team:showPlayer }
    requirements:
        player_id:  \d+

user_showMarket:
    pattern: /market
    defaults: {_controller: UserBundle:Market:listMarket }

user_createMarket:
    pattern: /market/create/{league_id}
    defaults: {_controller: UserBundle:Market:createMarket }
    requirements:
        league_id:  \d+

user_placeBid:
    pattern: /market/placebid/{player_id}/{bid}
    defaults: {_controller: UserBundle:Market:placeBid }
    requirements:
        player_id:  \d+
        bid:  \d+

user_sellPlayer:
    pattern: /market/sellPlayer/{player_id}
    defaults: {_controller: UserBundle:Market:sellPlayer }
    requirements:
        player_id:  \d+