user_home:
    pattern: /
    defaults: { _controller: UserBundle:User:index }

user_login:
    pattern: /login
    defaults: { _controller: UserBundle:User:login }

user_signup:
    pattern: /signup
    defaults: { _controller: UserBundle:User:signup }

user_loginAttempt:
    pattern:  /attempt/{username}/{password}
    defaults: { _controller: UserBundle:User:loginAttempt }
    requirements:
        _method: POST