user_index:
    pattern: /
    defaults: { _controller: UserBundle:User:index }

user_home:
    pattern: /home
    defaults: { _controller: UserBundle:User:home }

user_login:
    pattern: /login
    defaults: { _controller: UserBundle:User:login }

user_signup:
    pattern: /signup
    defaults: { _controller: UserBundle:User:signup }

user_loginAttempt:
    pattern: /loginAttempt
    defaults: { _controller: UserBundle:User:loginAttempt }

user_signupAttempt:
    pattern: /signupAttempt
    defaults: { _controller: UserBundle:User:signupAttempt }
    requirements:
        _method: POST

user_listTeams:
    pattern: /teams
    defaults: { _controller: UserBundle:User:listTeams }

user_newTeam:
    pattern: /leagues/newTeam
    defaults: { _controller: UserBundle:User:newTeam }

user_createTeam:
    pattern: /leagues/createTeam
    defaults: { _controller: UserBundle:User:createTeam }

user_listLeagues:
    pattern: /leagues
    defaults: { _controller: UserBundle:User:listLeagues }

user_newLeague:
    pattern: /leagues/newLeague
    defaults: { _controller: UserBundle:User:newLeague }

user_createLeague:
    pattern: /leagues/createLeague
    defaults: { _controller: UserBundle:User:createLeague }