user_index:
    pattern: /
    defaults: { _controller: UserBundle:User:index }

user_home:
    pattern: /home
    defaults: { _controller: UserBundle:User:home }

user_login:
    pattern: /login
    defaults: { _controller: UserBundle:User:login }
    requirements:
        _method: GET

user_signup:
    pattern: /signup
    defaults: { _controller: UserBundle:User:signup }
    requirements:
        _method: GET

user_loginAttempt:
    pattern: /login
    defaults: { _controller: UserBundle:User:loginAttempt }
    requirements:
        _method: POST

user_signupAttempt:
    pattern: /signup
    defaults: { _controller: UserBundle:User:signupAttempt }
    requirements:
        _method: POST

user_exit:
    pattern: /exit
    defaults: { _controller: UserBundle:User:exit }

user_listTeams:
    pattern: /teams
    defaults: { _controller: UserBundle:Team:listTeams }

user_leaguePassword:
    pattern: /teams/league/{league_id}
    defaults: { _controller: UserBundle:League:leaguePassword, league_password: 0 }
    requirements:
        league_id:  \d+
        _method: GET

user_checkLeaguePassword:
    pattern: /teams/league/{league_id}/{league_password}
    defaults: { _controller: UserBundle:League:leaguePassword, league_password: "league3" }
    requirements:
        league_id:  \d+
        _method: POST

user_newTeam:
    pattern: /teams/new/{league_id}
    defaults: { _controller: UserBundle:Team:newTeam }
    requirements:
        _method: GET
        league_id:  \d+

user_createTeam:
    pattern: /teams/create/{league_id}
    defaults: { _controller: UserBundle:Team:createTeam }
    requirements:
        _method: POST
        league_id:  \d+

user_listLeagues:
    pattern: /leagues/join
    defaults: { _controller: UserBundle:League:listLeagues }

user_newLeague:
    pattern: /leagues/new
    defaults: { _controller: UserBundle:League:newLeague }

user_createLeague:
    pattern: /leagues/create
    defaults: { _controller: UserBundle:League:createLeague }

user_showTeam:
    pattern: /teams/{league_id}/{team_id}/{edit}
    defaults: {_controller: UserBundle:Team:showTeam }

user_editEleven:
    pattern: /teams/edit
    defaults: {_controller: UserBundle:Team:editEleven }

user_updateEleven:
    pattern: /teams/update
    defaults: {_controller: UserBundle:Team:updateEleven }

user_showPlayer:
    pattern: /viewplayer/{player_id}
    defaults: {_controller: UserBundle:Team:showPlayer }

user_showMarket:
    pattern: /market
    defaults: {_controller: UserBundle:Market:listMarket }