user_index:
    pattern: /
    defaults: { _controller: UserBundle:User:index }

user_home:
    pattern: /home
    defaults: { _controller: UserBundle:User:home }

user_login:
    pattern: /login
    defaults: { _controller: UserBundle:User:login }

user_signup:
    pattern: /signup
    defaults: { _controller: UserBundle:User:signup }

user_loginAttempt:
    pattern: /loginAttempt
    defaults: { _controller: UserBundle:User:loginAttempt }

user_signupAttempt:
    pattern: /signupAttempt
    defaults: { _controller: UserBundle:User:signupAttempt }
    requirements:
        _method: POST

user_exit:
    pattern: /exit
    defaults: { _controller: UserBundle:User:exit }

user_listTeams:
    pattern: /teams
    defaults: { _controller: UserBundle:Team:listTeams }

user_newTeam:
    pattern: /teams/new
    defaults: { _controller: UserBundle:Team:newTeam }

user_createTeam:
    pattern: /teams/create
    defaults: { _controller: UserBundle:Team:createTeam }

user_joinLeague:
    pattern: /leagues/join
    defaults: { _controller: UserBundle:League:listLeagues }

user_newLeague:
    pattern: /leagues/new
    defaults: { _controller: UserBundle:League:newLeague }

user_createLeague:
    pattern: /leagues/create
    defaults: { _controller: UserBundle:League:createLeague }

user_showTeam:
    pattern: /teams/{league_id}/{team_id}/{modify}
    defaults: {_controller: UserBundle:Team:showTeam }

user_modifyEleven:
    pattern: /teams/modify
    defaults: {_controller: UserBundle:Team:modifyEleven }

user_updateEleven:
    pattern: /teams/update
    defaults: {_controller: UserBundle:Team:updateEleven }