fantasy_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: FantasyUserBundle:Default:index }

fantasy_user_main:
    pattern:     /home
    defaults: { _controller: FantasyUserBundle:Default:index }