admin_login:
    pattern: /login
    defaults: { _controller: AdminBundle:Security:login }

admin_login_check:
    pattern: /login_check

admin_logout:
    pattern: /logout

admin_home:
    pattern: /
    defaults: { _controller: AdminBundle:Admin:home }

admin_players:
    pattern: /players
    defaults: { _controller: AdminBundle:Admin:players }

admin_players_create:
    pattern: /players/create
    defaults: { _controller: AdminBundle:Admin:createPlayer }

admin_players_add:
    pattern: /players/add/{edit}
    defaults: { _controller: AdminBundle:Admin:addPlayer }

admin_players_list:
    pattern: /players/list/{edit}
    defaults: { _controller: AdminBundle:Admin:listPlayer }

admin_players_edit:
    pattern: /players/edit/{player_id}
    defaults: { _controller: AdminBundle:Admin:editPlayer }

admin_players_remove:
    pattern: /players/remove/{player_id}
    defaults: { _controller: AdminBundle:Admin:removePlayer }