admin_login:
    pattern: /login
    defaults: { _controller: AdminBundle:Security:login }

admin_login_check:
    pattern: /login_check

admin_logout:
    pattern: /logout

admin_home:
    pattern: /
    defaults: { _controller: AdminBundle:Admin:home }

admin_players:
    pattern: /players
    defaults: { _controller: AdminBundle:Admin:players }

admin_players_create:
    pattern: /players/create
    defaults: { _controller: AdminBundle:Admin:createPlayer }

admin_players_add:
    pattern: /players/add/{edit}/{player_id}
    defaults: { _controller: AdminBundle:Admin:addPlayer }

admin_players_list:
    pattern: /players/list/{edit}
    defaults: { _controller: AdminBundle:Admin:listPlayer }

admin_players_edit:
    pattern: /players/edit/{player_id}
    defaults: { _controller: AdminBundle:Admin:editPlayer }

admin_players_remove:
    pattern: /players/remove/{player_id}
    defaults: { _controller: AdminBundle:Admin:removePlayer }

admin_leagues:
    pattern: /leagues
    defaults: { _controller: AdminBundle:Admin:leagues }

admin_leagues_create:
    pattern: /leagues/create
    defaults: { _controller: AdminBundle:Admin:createLeague }

admin_leagues_add:
    pattern: /leagues/add/{edit}/{league_id}
    defaults: { _controller: AdminBundle:Admin:addLeague }

admin_leagues_list:
    pattern: /leagues/list/{edit}
    defaults: { _controller: AdminBundle:Admin:listLeague }

admin_leagues_edit:
    pattern: /leagues/edit/{league_id}
    defaults: { _controller: AdminBundle:Admin:editLeague }

admin_leagues_remove:
    pattern: /leagues/remove/{league_id}
    defaults: { _controller: AdminBundle:Admin:removeLeague }

admin_update_markets:
    pattern: /leagues/update
    defaults: { _controller: AdminBundle:Admin:updateMarkets }